name: Build Client

on:
    workflow_dispatch:

permissions:
    contents: write

jobs:
    run-script:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: '18'
            - run: npm install
            - run: npx tsx src/build-client.ts